include: package:very_good_analysis/analysis_options.3.0.0.yaml
linter:
  rules:
    avoid_catching_errors: false
    exclude:
      - "**/**.reflectable.dart"
    include:
      - "lib/**.dart"
      - "**/**.dart"
