name: backend
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  alfred:
    git: https://github.com/rknell/alfred.git
  collection: ^1.16.0
  dart_jsonwebtoken: ^2.4.0
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  get_it: ^7.2.0
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation: ^4.4.0
  mongo_dart: ^0.7.4
  mongo_dart_query: ^1.0.2
  test: ^1.20.1

dev_dependencies:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  json_serializable: ^6.1.5
  very_good_analysis: ^2.4.0
