name: backend
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  alfred: ^0.1.5+3
  alfredito: ^0.0.1+1
  dart_jsonwebtoken: ^2.4.1
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  http: ^0.13.4
  http_parser: ^4.0.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  mailer: ^5.1.0
  meta: ^1.7.0
  mongo_dart: ^0.7.4
  mongo_dart_query: ^1.0.2
  queue: ^3.1.0+1
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  json_serializable: ^6.1.5
  recharge: ^0.1.0
  very_good_analysis: ^2.4.0
