name: backend
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  alfred: ^0.1.5+3
  alfredito: ^0.0.1+1
  database:
    path: packages/database
  dotenv: ^4.0.1
  mongo_dart: ^0.7.4+1

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  recharge: ^0.1.0
  very_good_analysis: ^3.0.0
