name: backend
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  alfred: ^0.1.5+3
  alfredito: ^0.0.1+1
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^4.0.1

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
